### ISSUE TITLE
Fix "insufficient funds to pay for pending and new transaction" when liquidating

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#27]
```
Error: Returned error: insufficient funds to pay for pending and new transaction
    at Object.ErrorResponse (/home/ana/sovryn/sovryn-node/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/ana/sovryn/sovryn-node/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/ana/sovryn/sovryn-node/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  data: null
}
```

**Comment by Bitcoinera** [comment]
Probably just a misleading error message, hiding the real reason. The truth is that there are 3 loans I could liquidate but it something is preventing it from happening

**Comment by Bitcoinera** [comment]
Mmm, it seems the issue is actually related to balance... I'm sending one sat more than I actually have :thinking:  This shouldn't be happening at all 

![image](https://user-images.githubusercontent.com/40721795/110526454-19614200-8116-11eb-9428-aae7209b763c.png)

![image](https://user-images.githubusercontent.com/40721795/110526509-2b42e500-8116-11eb-86ca-ba5ad766db77.png)
