### ISSUE TITLE
VM execution error: transaction reverted

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#29]
??? What happened:

```
Error receiving user loans from 500 to: 600
Error: Returned error: VM execution error: transaction reverted
    at Object.ErrorResponse (/home/ana/sovryn/sovryn-node/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/ana/sovryn/sovryn-node/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/ana/sovryn/sovryn-node/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/ana/sovryn/sovryn-node/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  data: null
}
```

**Comment by Bitcoinera** [comment]
Using this address, it seems all transactions got reverted? 0x35F9f4A6ef69C1D0609821c014a2Ea0bc277C6f2

**Comment by Bitcoinera** [comment]
Strangely this was only happening on the first run. I guess it is nothing we can control since it comes from the web3 module and we are already handling this error in the lines 64 to 70 in `scanner.js`, so I guess everything is OK. Closing this for now.

**Comment by Bitcoinera** [comment]
Reopening since this issue is coming and going

**Comment by Bitcoinera** [comment]
Closing this, as this error can be produced by so many different reasons, it cannot be reduced to one single cause

**Comment by jjmr007** [comment]
Hello Bitcoinera: you can debug reverted transactions following these recommendations:

https://stackoverflow.com/questions/66144175/is-there-a-way-to-debug-transactions-in-rsk-network-which-could-be-the-best-way

all you need is a node with the debug feature enabled (I think Sovryn nodes already have it) and follow the procedure.. just change the localhost: http://localhost:4444 for the actual URL of our Sovryn node.

Hope it work for you!

**Comment by Bitcoinera** [comment]
> Hope it work for you!

Hey, thank you so much!

This is an awesome tip!

EDIT: Hey, but it doesn't seem to be the same error. This is internal error the one you are treating there and what I'm getting is "transaction reverted" :thinking:  So the problem is coming from the SC somehow. But maybe this also works
